companieshouse/limited-partnerships-web

Makefile, package.json
uncomment makefile targets for pipeline security check task to run
```
``` …
=> Uncomment makefile targets

locales/cy/translations.json, locales/en/translations.json, package.json, src/presentation/test/integration/localisation.test.ts, src/presentation/test/integration/registration/name.test.ts, src/views/includes/save-and-continue-button.njk, src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-211
Change the text on the Name page to use localisation and add text to the EN and CY locales/translations files
```
``` …
=> LP-279 Add i18n text to name page

src/config/constants.ts, src/test/global.setup.ts
NA
We are getting a property not found error when deploying app into CI-Dev, and it looks like the CHS_API_KEY that it is looking for is no longer used in the service, so removing it to see if it fixes the issue.
```
``` …
=> Remove API key from constants

package-lock.json, package.json
NA
types/express 5.0 is not compatible with express 4.21 so changing to use a compatible types library. 
https://github.com/expressjs/express/issues/5987
```
```
- …
=> Use a compatible express types dependency

src/views/name.njk, src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-382
Change the name page radio buttons to only record matomo event on button press and renamed
Event Limited Partnerships name - namepage-name
to
Event Limited Partnerships name - name
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
=> LP-382 Change matomo on name page

src/presentation/test/integration/localisation.test.ts, src/presentation/test/integration/registration/check-your-answers.test.ts, src/presentation/test/integration/registration/email.test.ts, src/presentation/test/integration/registration/general-partner-choice.test.ts, src/presentation/test/integration/registration/general-partners.test.ts, src/presentation/test/integration/registration/limited-partner-choice.test.ts, src/presentation/test/integration/registration/limited-partners.test.ts, src/presentation/test/integration/registration/name.test.ts, src/presentation/test/integration/registration/postcode-registered-office-address.test.ts, src/test/test-utils.ts
NA
Removing duplication of the setLocalesEnabled function used in the tests by importing it
```
``` …
=> Remove duplication of setLocalesEnabled test function

src/views/postcode-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-278
Data event ids were present on the page for the AC2 manual link, this was not logging anything in Matomo so have altered this to run code on click similar to what we have for the submit button on other pages.
Updated the find button to include tracking also based on what we have for buttons on other pages. 
Not been able to fulfil AC5 (now removed) dues to complications in obtaining error message data dynamically so all we see in Matomo is "Submit" regardless; would propose a separate ticket to address error messages.
```
```
- …
=> LP-278 Matomo addess postcode lookup page

locales/cy/translations.json, locales/en/translations.json, src/application/service/AddressLookUpService.ts, src/presentation/test/integration/registration/address/enter-registered-office-address.test.ts, src/views/enter-registered-office-address.njk, src/views/includes/errors.njk, src/views/includes/validators.njk
https://companieshouse.atlassian.net/browse/LP-221
Add js validation messages for the manual address entry page
Change the country select option to use GB- values
Refactored translations for the manual address entry page 
```
``` …
=> LP-221 fix validation messages on manual entry registered office address page

src/views/pages/address/enter-address-form.njk
https://companieshouse.atlassian.net/browse/LP-483
Added error pop-up on country input drop down when the country does not match the jurisdiction.
```
```
- types …
=> LP-483 Error to country input when wrong jurisdiction

src/views/add-general-partner-person.njk
https://companieshouse.atlassian.net/browse/LP-530
* Missing attributes added to the Gov checkbox definition to ensure correct behaviour
* Also added the missing 'isPageHeading' attribute
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
=> LP-530 Ensure check-box still ticked after API error

src/views/company-number.njk
https://companieshouse.atlassian.net/browse/LP-517
For the transitions company number page
Updated regex in the nunjucks template to tolerate leading and trailing whitespaces.
Given that the template validates immediately as soon as the user enters the value, there isn't time to strip the spaces. This would be better as the subsequent lookup will reject any number that has a leading space.
You can add '-' for variables but not sure where it would go for values.
```
```
- …
=> LP-517 Allow regex to tolerate leading and trailing spaces

src/presentation/test/integration/registration/name.test.ts, src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-637
If Ids are present in the URL then update submission name and don't create new transaction/submission
The form was always posting to props.currentUrl which was limited-partnerships/name, so removed the form action so it posts using the browser url which will include the ids if they are present.
```
```
- …
=> LP-637 Make name page update existing submission if IDs present

locales/cy/translations.json, locales/en/translations.json, src/presentation/controller/addressLookUp/Controller.ts, src/views/confirm-general-partner-usual-residential-address.njk, src/views/pages/address/confirm-address-form.njk
https://companieshouse.atlassian.net/browse/LP-554
Fixed function in addressLookUp controller to correctly set data for general partner confirm page.
Changed translations to display correct text on page
Changed confirm general partner page template to correctly set data if already present.
bug fix for post-code missing leaving a blank space
```
```
- BREAKING …
=> Lp 554 confirm general partner usual residential address

locales/cy/translations.json, locales/en/translations.json, src/presentation/test/integration/registration/check-your-answers.test.ts, src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-506
Added jurisdiction field with change link
Updated test to check for jurisdiction value from the api.
Not sure if there are changes required for ROA etc to make them acceptable, I have assumed that it would be a manual change for the user as they retake the journey.
```
```
- BREAKING CHANGE: a commit that has a …
=> LP-506 Check your answers jurisdiction field

src/presentation/test/integration/registration/check-your-answers.test.ts, src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-732
* Change link for jursidiction now only shown on the 'check your answers' page if a non Scottish Partnership is being created
* Tests added to check presence of the link
```
``` …
=> LP-732 Control presence of jurisdiction change link

src/presentation/controller/addressLookUp/Controller.ts, src/presentation/test/integration/registration/address/enter-registered-office-address.test.ts
https://companieshouse.atlassian.net/browse/LP-667
Make sure the partnership name is still on the page when we get a jurisdiction validation error
```
```
- types …
=> LP-667 Don't lose name on jurisdiction validation

src/presentation/controller/addressLookUp/Controller.ts, src/presentation/test/integration/registration/generalPartner/address/postcode-general-partner-correspondence-address.test.ts, src/presentation/test/integration/registration/generalPartner/address/postcode-general-partner-principal-office-address.test.ts, src/presentation/test/integration/registration/generalPartner/address/postcode-general-partner-usual-residential-address.test.ts
https://companieshouse.atlassian.net/browse/LP-693
https://companieshouse.atlassian.net/browse/LP-739
* Ensure General Partner forename and surname still show when an address postcode error fires on URA
* Fix applies to correspondence (service) and principal address also
* Unit tests added to validate behaviour
```
```
- BREAKING CHANGE: a commit that has a …
=> LP-693 Show GP Name when postcode address error fires

locales/cy/translations.json, locales/en/translations.json, src/views/pages/address/postcode-form.njk
https://companieshouse.atlassian.net/browse/LP-721
There was an accessibility error on the postcode pages due to the entry field having no label.
Other forms use the label to add description text to the field but postcode was using a hint (taken from prototype)
To fix I have changed from using a hint to a label.
```
```
- BREAKING CHANGE: a commit that has a …
=> LP-721 Fix a11y issue on postcode pages for missing label

package-lock.json, package.json, src/views/includes/jurisdiction-form.njk, src/views/includes/jurisdiction-scotland.njk
[LP-722](https://companieshouse.atlassian.net/browse/LP-722)
Switch Jurisdiction use API enumeration keys. These keys are then used within a change to chips filing consumer that will map these keys to their specific chips counterpart during processing.
Relates to the following API changes - https://github.com/companieshouse/limited-partnerships-api/pull/131
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
=> lp-722: Switch jurisdiction values to match api-enumeration keys

src/presentation/controller/addressLookUp/Controller.ts, src/presentation/controller/global/Controller.ts, src/presentation/controller/registration/GeneralPartnerController.ts, src/presentation/controller/registration/LimitedPartnerController.ts, src/presentation/controller/registration/LimitedPartnershipController.ts, src/presentation/controller/transition/TransitionController.ts
N/A
Fix sonar issue on RequestHandler return type
removed RequestHandler from function signature to let TypeScript infer the correct return type.
```
```
- types …
=> Sonar fix for RequestHandler promise return type

src/config/app-config.ts, src/presentation/test/integration/error-404.test.ts, src/presentation/test/integration/error-500.test.ts
N/A
Make sure the localisation middleware does not run when the healthcheck endpoint is called (every 3-5 seconds in Live)
The tests changed were using healthcheck url and checking for the translated text to be returned. Now we have excluded healthcheck from the localisation, no text is returned so tests have been changed to use WHICH_TYPE, which will use localisation and get the text returned in the response.
```
```
- feat: a commit that introduces a new feature to the …
=> Exclude the healthcheck from running the localisation middleware

locales/cy/translations.json
https://companieshouse.atlassian.net/browse/LP-548
Changed error message in CY translations for nameOrNumberLength to 200.
Looks like english translation was already correct.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of …
=> LP-548 changed nameOrNumberLength error message in cy translation

src/presentation/test/integration/registration/check-your-answers.test.ts, src/views/check-your-answers.njk, src/views/includes/macros.njk, src/views/pages/address/choose-address-form.njk
https://companieshouse.atlassian.net/browse/LP-813
Updated macros to include country added flag to make this optional as it will not be required in all instances; only on the check your answers page.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
=> Lp 813 Ensure country is displayed in addresses values

src/presentation/controller/addressLookUp/Controller.ts, src/presentation/test/integration/registration/generalPartner/address/enter-general-partner-correspondence-address.test.ts, src/presentation/test/integration/registration/generalPartner/address/enter-general-partner-principal-office-address.test.ts, src/presentation/test/integration/registration/generalPartner/address/enter-general-partner-usual-residential-address.test.ts, src/presentation/test/integration/registration/limitedPartner/address/enter-limited-partner-principal-office-address.test.ts, src/presentation/test/integration/registration/limitedPartner/address/enter-limited-partner-usual-residential-address.test.ts
https://companieshouse.atlassian.net/browse/LP-754
* General Partner and Limited Partner names now display on the 'enter manual address' screens if a typescript validation error is raised
* Tests added for all pages where this was occurring
```
``` …
=> LP-754 Ensure partner name displayed when validation error is raised

src/presentation/controller/registration/LimitedPartnerController.ts, src/presentation/test/integration/registration/limitedPartner/review-limited-partners.test.ts
https://companieshouse.atlassian.net/browse/LP-798
Review page get function - added interceptor to redirect to the start of the limited partner journey when the list of limited partners is empty.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING …
=> LP-798 Redirect from remove when limited partner list is empty

src/presentation/controller/registration/routing/generalPartner.ts, src/presentation/test/integration/registration/generalPartner/review-general-partners.test.ts, src/views/general-partners.njk, src/views/includes/configurable-back-link.njk, src/views/review-general-partners.njk
https://companieshouse.atlassian.net/browse/LP-903
* Link now correctly takes user back to SIC codes page or PPOB page based on LP type
* New configurable include added for 'Back' link and also used on the General Partners choice page
* Test added
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
=> LP-903 Fix 'Back' link on the Review General Partners page

src/views/enter-general-partner-correspondence-address.njk, src/views/enter-general-partner-principal-office-address.njk, src/views/enter-general-partner-usual-residential-address.njk, src/views/enter-limited-partner-principal-office-address.njk, src/views/enter-limited-partner-usual-residential-address.njk
https://companieshouse.atlassian.net/browse/LP-915
When the user selects "overseas" for all general and limited partner addresses, then the change ensures that the postcode field is highlighted on the manual entry page for invalid format.
```
``` …
=> LP-915 Highlight postcode error for overseas addresses
