- README.md
- package-lock.json
- package.json
- src/app.ts
- src/bin/www.ts
- src/config/index.ts
- src/controllers/index.ts
- src/controllers/start.controller.ts
- src/routes/index.ts
- src/utils/environment.value.ts
- src/utils/logger.ts
- tsconfig.json
- views/start.html
https://companieshouse.atlassian.net/browse/LP-156
A basic skeleton app
run 'npm i' to install packages
followed by
'npm run build' to compile
and 'npm run start' to start the service
use localhost:3000/limited-partnerships/start to view the test page
/limited-partnerships/ is not the decided domain name so may change.
> LP-156 Create skeleton app

- Makefile
- README.md
- package-lock.json
- package.json
- sonar-project.properties
https://companieshouse.atlassian.net/browse/LP-154
* Unused Makefile targets are currently commented out
> LP-154 Add Makefile and Sonar config

- .github/dependabot.yml
https://companieshouse.atlassian.net/browse/LP-114
Add dependabot
```
``` …
> LP-114 Add dependabot config

- eslint.config.mjs
- package.json
https://companieshouse.atlassian.net/browse/LP-98
Fix lint issues in the lint config file
Add lint config file to lint path
```
``` …
> LP-98 Fix lint issues in lint config file

- ecs-image-build/Dockerfile
- ecs-image-build/docker_start.sh
- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
- terraform/groups/ecs-service/vault-providers/approle
- terraform/groups/ecs-service/vault-providers/token
- terraform/groups/ecs-service/vault-providers/userpass
- terraform/groups/ecs-service/vault.tf
- terraform/groups/ecs-service/version
https://companieshouse.atlassian.net/browse/LP-130
ecs config
```
``` …
> Lp 130 add ecs config for lp

- sonar-project.properties
correct sonar.test to right location 
```
``` …
> change sonar test location

- terraform/groups/ecs-service/main.tf
Fix tf resource, incorrectly named.
```
``` …
> fix tf config

- sonar-project.properties
add blank line for pipeline to pick up changes. 
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …
> add blank line for pipeline to pick up change

- terraform/groups/ecs-service/locals.tf
NA
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others, …
> correct healthcheck path location

- jest.config.js
- src/test/error-pages.test.ts
- src/test/setup-jest.ts
https://companieshouse.atlassian.net/browse/LP-157
following the jest guide - https://jestjs.io/docs/configuration#setupfilesafterenv-array
We can add mocks into a setup file that runs before each test file.
To fix the timeout issue, each test file needs ioredis mocked, so we can add it to the new setup-jest.ts file so it will run before each test file.
We can also add common mocks in here in the future to reduce test file size and duplicated code.
```
```
- feat: a commit …
> LP-157 Fix test timeout

- .dockerfile
- .dockerignore
- Dockerfile
- docker_start.sh
https://companieshouse.atlassian.net/browse/LP-142
create docker chs development web
```
``` …
> create docker chs development web

- terraform/groups/ecs-service/main.tf
update tf modules, mount points for read only access included at module level and defaults set to true.
- [ x ] UI changes meet accessibility criteria
```
```
- …
> update tf modules

- src/service/limited-partnerships-service.ts
- src/test/limited.partnership.test.ts
https://companieshouse.atlassian.net/browse/LP-201
Create a new service for Limited Partnerships to allow interaction between Web and API
```
```
- types other …
> LP-201 Create a new service for Limited Partnerships

- src/config/index.ts
- src/test/global.setup.ts
- src/utils/localise.ts
https://companieshouse.atlassian.net/browse/LP-167
* Removed as the location is inherently 'hard-coded' due to the project folder structure
```
```
- types other …
> LP-167 Removal of the 'locale location' env property

- package-lock.json
NA
npm audit fixes for 2 high security vulnerabilities 
@eslint/plugin-kit  <0.2.3
Severity: high
Regular Expression Denial of Service (ReDoS) in @eslint/plugin-kit - https://github.com/advisories/GHSA-7q7g-4xm8-89cq
fix available via `npm audit fix`
node_modules/@eslint/plugin-kit
cross-spawn  <7.0.5
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
```
```
- feat: …
> Security fixes using npm audit fix

- src/application/registration/Service.ts
- src/config/constants.ts
- src/domain/IRegistrationGateway.ts
- src/domain/entities/TransactionLimitedPartnership.ts
- src/infrastructure/gateway/LimitedPartnershipGatewayBuilder.ts
- src/infrastructure/gateway/RegistrationGateway.ts
- src/infrastructure/gateway/RegistrationInMemoryGateway.ts
- src/presentation/controller/registration/Controller.ts
- src/presentation/test/integration/registration/createTransactionAndFirstSubmission.test.ts
- src/presentation/test/unit/registration/createTransactionAndFirstSubmission.spec.ts
- src/test/global.setup.ts
https://companieshouse.atlassian.net/browse/LP-216
create transaction
```
``` …
> lp-216 : create registration transaction

- src/application/registration/Service.ts
- src/domain/IRegistrationGateway.ts
- src/infrastructure/gateway/LimitedPartnershipGatewayBuilder.ts
- src/infrastructure/gateway/RegistrationGateway.ts
- src/infrastructure/gateway/RegistrationInMemoryGateway.ts
- src/presentation/test/integration/registration/createTransactionAndFirstSubmission.test.ts
https://companieshouse.atlassian.net/browse/LP-217
https://companieshouse.atlassian.net/browse/LP-203
create first submission
```
``` …
> lp-217 : create first submission

- src/views/layout.njk
https://companieshouse.atlassian.net/browse/LP-213
Adding styling to the language navigation bar
```
``` …
> LP-213 Add styling to language selection bar

- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-290
Add html and javascript validation for partnership name: 
- Cannot start or end with a space
- Needs to be at least 2 characters
- Name plus name suffix cannot be greater than 160 characters
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …
> LP-290 add html validation for partnership name

- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-289
Fix for hint text as it was not working.
```
``` …
> LP-289 Fix hint links text

- src/presentation/controller/registration/Controller.ts
- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-300
pass query parameters to view
```
``` …
> lp-300 : pass query parameters to view

- src/views/pages/name/private-limited-partnership-name.njk
https://companieshouse.atlassian.net/browse/LP-310
The script is in common between pages, so there are few changes to be made:
- indentation
- naming
- set min length from 3 to 1.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …
> LP-310 Private name page ending and validation

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/name.test.ts
- src/views/name.njk
- src/views/pages/name/private-limited-partnership-name-scotland.njk
https://companieshouse.atlassian.net/browse/LP-194
* New translation texts added, some existing ones reused
* New name page
* Tests added
```
```
- types other …
> LP-194 Implement 'Scottish Private Fund Limited Partnership name' page

- locales/cy/translations.json
- locales/en/translations.json
- src/infrastructure/gateway/RegistrationGateway.ts
- src/presentation/controller/registration/PageType.ts
- src/presentation/controller/registration/Routing.ts
- src/presentation/test/integration/registration/general-partner-choice.test.ts
- src/routes/registration.ts
- src/views/general-partner-choice.njk
https://companieshouse.atlassian.net/browse/LP-236
Page template, routing - back and forward and html validation for the general partner choice page.
Not displaying the partnership name.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
> Lp 236 general partner choice page

- locales/cy/translations.json
- locales/en/translations.json
- src/config/constants.ts
- src/presentation/controller/AbstractController.ts
- src/presentation/controller/registration/Controller.ts
- src/presentation/controller/registration/PageType.ts
- src/presentation/controller/registration/Routing.ts
- src/presentation/test/integration/registration/createTransactionAndFirstSubmission.test.ts
- src/presentation/test/integration/registration/limited-partner-choice.test.ts
- src/routes/registration.ts
- src/views/general-partners.njk
- src/views/limited-partner-choice.njk
https://companieshouse.atlassian.net/browse/LP-239
Add the limited partner choice page
```
``` …
> LP-239 Add the limited partner choice page

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/name.test.ts
- src/views/pages/name/private-limited-partnership-name-scotland.njk
- src/views/pages/name/private-limited-partnership-name.njk
- src/views/pages/name/scottish-limited-partnership-name.njk
https://companieshouse.atlassian.net/browse/LP-328
* Reduced the duplication of text resources
```
``` …
> LP-328 Refactored the text resources for the LP Name pages

- src/views/limited-partner-choice.njk
https://companieshouse.atlassian.net/browse/LP-239
Replace "Save and Continue" button with "Continue" button
```
``` …
> LP-239 Amend Submit button text for limited partner

- package-lock.json
NA
2 moderate security vulnerabilities fixed by running 'npm audit fix'
```
``` …
> Apply latest npm audit fixes

- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-313
name options use new partnership_type
```
``` …
> lp-313 : name options use new partnership_type

- src/presentation/controller/AbstractController.ts
- src/presentation/controller/global/Controller.ts
- src/presentation/controller/registration/Controller.ts
- src/views/includes/back-link.njk
https://companieshouse.atlassian.net/browse/LP-318
persists language across pages
```
``` …
> fix : lp-318 - persists language across pages

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/email.test.ts
- src/presentation/test/integration/registration/general-partner-choice.test.ts
- src/presentation/test/integration/registration/general-partners.test.ts
- src/presentation/test/integration/registration/limited-partner-choice.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/presentation/test/integration/registration/name.test.ts
- src/views/email.njk
- src/views/general-partner-choice.njk
- src/views/general-partners.njk
- src/views/includes/page-title.njk
- src/views/layout.njk
- src/views/limited-partner-choice.njk
- src/views/limited-partners.njk
- src/views/name.njk
- src/views/start.njk
- src/views/which-type.njk
Go through each page add a title block and link it to the title in the language json files and then adding the required format.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …
> LP-298 Ensure tab heading is correct

- src/config/app-config.ts
- src/config/constants.ts
- src/middlewares/service-availability.middleware.ts
- src/presentation/test/integration/service-availability.test.ts
- src/test/global.setup.ts
- src/views/service-unavailable.njk
https://companieshouse.atlassian.net/browse/LP-320
Add a service unavailable page to be shown when env property SHOW_SERVICE_UNAVAILABLE_PAGE is set to 'true'
```
``` …
> LP-320 Add service unavailable middleware and page

- src/application/registration/Service.ts
- src/config/constants.ts
- src/infrastructure/gateway/api.ts
- src/infrastructure/gateway/registration/RegistrationGateway.ts
- src/presentation/controller/registration/Controller.ts
- src/presentation/test/integration/registration/gateway.test.ts
- src/presentation/test/unit/registration/createTransactionAndFirstSubmission.spec.ts
- src/presentation/test/unit/registration/updateSubmission.spec.ts
- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-332
add makeApiCallWithRetry function
```
``` …
> lp-332 : add makeApiCallWithRetry

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/partnership-type.test.ts
- src/views/which-type.njk
https://companieshouse.atlassian.net/browse/LP-326
Remove SQP from Partnerships options list
```
``` …
> Lp326 remove sqp as option on partnership page

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-375
bug fix for titles and welsh text 
```
```
- types other than …
> LP298 - LP375 bug fix for welsh text

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
remove log_level as log_level defined in .env file in ecs-service-configs
```
``` …
> remove log_level

- locales/cy/translations.json
- locales/en/translations.json
- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-327
update radio buttons in name page
```
``` …
> lp-327 : update radio buttons in name page

- src/presentation/test/integration/registration/email.test.ts
- src/presentation/test/integration/registration/general-partner-choice.test.ts
- src/presentation/test/integration/registration/general-partners.test.ts
- src/presentation/test/integration/registration/limited-partner-choice.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/views/email.njk
- src/views/general-partner-choice.njk
- src/views/general-partners.njk
- src/views/includes/proposed-name.njk
- src/views/limited-partner-choice.njk
- src/views/limited-partners.njk
https://companieshouse.atlassian.net/browse/LP-316
Add proposed name to pages
```
``` …
> Add proposed name to pages

- terraform/groups/ecs-service/variables.tf
test TF code deployment to see if pipeline workflows function correctly and in order
```
``` …
> terraform deployment to test pipeline

- locales/cy/translations.json
https://companieshouse.atlassian.net/browse/LP-375
Amend Welsh text on General Partners page
```
``` …
> amend Welsh text on general partner choice page

- locales/en/translations.json
amend tab heading text title 
```
``` …
> amend tab heading text title

- package-lock.json
- package.json
- src/infrastructure/gateway/registration/RegistrationGateway.ts
https://companieshouse.atlassian.net/browse/LP-368
Changed to use the builder to create lp instance from the record data passed into the patch call function and updated the arguments using this build.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
> LP-368 Patch sdk function call - convert record data into lp model

- src/views/name.njk
- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-266
added data event ids with structure 
namePage-{field}-{radio button}
for the radio button form fields and
namePage-{field}
for the name input form field
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
> LP-266 Matomo tracking for the name page

- locales/cy/translations.json
- locales/en/translations.json
amend welsh text and add a question mark
```
``` …
> amend Welsh text and add a question mark

- src/presentation/test/integration/registration/email.test.ts
- src/views/email.njk
> fix tab tiltle bug

- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-327
* Use unique option button ids for welsh options so that selection works correctly
```
```
- types other than …
> LP-327 Ensure Welsh option text selection works

- src/views/email.njk
https://companieshouse.atlassian.net/browse/LP-277
add Matomo to register email address page
```
``` …
> add matomo to register email address page

- src/infrastructure/gateway/api.ts
https://companieshouse.atlassian.net/browse/LP-332
fix new request after refresh token
```
``` …
> fix : lp-332  - spread args on new request

- src/views/limited-partner-choice.njk
https://companieshouse.atlassian.net/browse/LP-384
Added Matomo tracking to the submit button so as to track the click event and record the radio button selection.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …
> LP-384 Limited partner choice - matomo

- src/views/general-partner-choice.njk
https://companieshouse.atlassian.net/browse/LP-383
* Choice now recorded in Matomo when user clicks continue button
```
``` …
> LP-383 Matomo general partner choice

- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-428
Fix broken aria link on name ending field
```
``` …
> LP-428 Fix broken aria link on name page

- src/views/choose-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-409
validation fires to tell me to select an address
```
``` …
> validation fires to tell me to select an address

- src/presentation/controller/addressLookUp/Controller.ts
https://companieshouse.atlassian.net/browse/LP-397
pass current data to screen if re-render due to error
```
```
- types other than `fix:` and `feat:` are allowed, …
> lp-397 : pass current data to screen if re-render due to error

- locales/cy/translations.json
- locales/en/translations.json
- src/application/service/AddressLookUpService.ts
- src/infrastructure/gateway/addressLookUp/AddressLookUpInMemoryGateway.ts
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/choose-registered-office-address.test.ts
- src/presentation/test/integration/registration/gateway_addressLookUp.test.ts
- src/views/choose-registered-office-address.njk
- src/views/includes/macros.njk
https://companieshouse.atlassian.net/browse/LP-407
Get list of address from postcode lookup service and populate choose registered office address page
```
```
- …
> LP-407 Populate address list on choose ROA screen

- src/middlewares/error.middleware.ts
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/choose-registered-office-address.test.ts
- src/routes/addressLookUp.ts
- src/test/setup-jest.ts
- src/views/choose-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-408
Capture the selected address from choose registered office address page and add to cache
```
```
- types other …
> LP-408 Get select address from choose registered office address page

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Removing the duplicate desired_task_count from the live vars
```
``` …
> Removing duplicate desired_task_count from live vars

- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-456
Fix the name ending on check your answers page
```
``` …
> LP-456 Fix name ending on check your answers page

- locales/cy/translations.json
- locales/en/translations.json
- src/views/includes/macros.njk
- src/views/name.njk
- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-479
native html error message using i18n (translations) - name page
```
``` …
> native html error message using i18n (translations)

- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/presentation/test/integration/registration/email.test.ts
- src/presentation/test/integration/registration/general-partner-choice.test.ts
- src/presentation/test/integration/registration/general-partners.test.ts
- src/presentation/test/integration/registration/limited-partner-choice.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/views/check-your-answers.njk
- src/views/includes/proposed-name.njk
https://companieshouse.atlassian.net/browse/LP-471
* Now output in uppercase at the top of screens
* Also output in uppercase on the 'check your answers' screen
* Amended unit tests
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
> LP-471 Output name and name ending in uppercase on pages

- src/views/postcode-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-470
postcode input size
```
``` …
> lp-470 : postcode input size

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-479
Update name error message
```
``` …
> lp-479 : update name error message

- src/views/includes/jurisdiction-form.njk
- src/views/includes/jurisdiction-scotland.njk
https://companieshouse.atlassian.net/browse/LP-458
ACs 1-2 Added Matomo tracking to the save and continue button for both variants of the jurisdiction page.
ACs 3-4 Included in common content for the pages. 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
> LP-458 Matomo for jurisdiction page

- src/presentation/controller/AbstractController.ts
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/controller/global/Controller.ts
- src/presentation/controller/registration/Controller.ts
N/A
refactor - move request extraction to AbstractController
```
``` …
> move request extraction to AbstractController

- src/views/enter-registered-office-address.njk
- src/views/includes/save-and-continue-button.njk
https://companieshouse.atlassian.net/browse/LP-389
Added a data even id to the save and continue button
```
```
- types other than `fix:` and `feat:` are allowed, …
> LP-389 Matomo manual registered office address page

- src/views/pages/address/postcode-form.njk
https://companieshouse.atlassian.net/browse/LP-398
reset postcode error
```
``` …
> fix lp-398 : reset postcode error

- src/presentation/controller/registration/Routing.ts
https://companieshouse.atlassian.net/browse/LP-234
fix import issue after merging
```
``` …
> fix issue after merging

- src/views/term.njk
https://companieshouse.atlassian.net/browse/LP-234
term page - add attribute required
```
``` …
> lp-234 : term page - add atrribute required

- src/infrastructure/gateway/limitedPartnership/LimitedPartnershipInMemoryGateway.ts
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/address/confirm-registered-office-address.test.ts
- src/views/confirm-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-387
Fixed confirm page to send address data
```
``` …
> Lp 387 fixed confirm address

- src/presentation/controller/registration/Routing.ts
https://companieshouse.atlassian.net/browse/LP-533
routing fix for previousURL from the term page
```
``` …
> LP-533 back link on term page redirects to correct page

- src/presentation/controller/addressLookUp/Routing.ts
- src/views/choose-principal-place-of-business-address.njk
- src/views/choose-registered-office-address.njk
- src/views/pages/address/choose-address-form.njk
https://companieshouse.atlassian.net/browse/LP-534
Added data bucket to address routing and changed template to include correct PageType
```
```
- types other than …
> Lp 534 address not on list redirect

- src/views/enter-principal-place-of-business-address.njk
- src/views/enter-registered-office-address.njk
- src/views/pages/address/enter-address-form.njk
https://companieshouse.atlassian.net/browse/LP-532
fix common data between pages
```
``` …
> lp-532 : fix common data between pages

- src/views/enter-principal-place-of-business-address.njk
- src/views/enter-registered-office-address.njk
- src/views/pages/address/enter-address-form.njk
https://companieshouse.atlassian.net/browse/LP-509
Removed Matomo event triggers for input fields
Added proposed name to top of manual entry pages
```
```
- types …
> LP-509 - Matomo interaction principal manual entry page

- src/application/service/AddressLookUpService.ts
- src/infrastructure/gateway/addressLookUp/AddressLookUpInMemoryGateway.ts
- src/presentation/test/integration/registration/address/postcode-registered-office-address.test.ts
https://companieshouse.atlassian.net/browse/LP-535
format postcode for comparison
```
``` …
> lp-535 : format postcode for comparison

- src/application/service/GeneralPartnerService.ts
- src/application/service/LimitedPartnershipService.ts
- src/application/service/utils.ts
- src/config/IDependencies.ts
- src/config/constants.ts
- src/config/dependencies.ts
- src/config/dev-dependencies.ts
- src/domain/IGeneralPartnerGateway.ts
- src/domain/entities/GeneralPartner.ts
- src/infrastructure/gateway/generalPartner/GeneralPartnerGateway.ts
- src/infrastructure/gateway/generalPartner/GeneralPartnerInMemoryGateway.ts
- src/presentation/controller/AbstractController.ts
- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/test/integration/mock/sdkMock.ts
- src/presentation/test/integration/registration/add-general-partner.test.ts
- src/presentation/test/integration/registration/cache.test.ts
- src/presentation/test/integration/registration/gateway/email.test.ts
- src/routes/registration.ts
https://companieshouse.atlassian.net/browse/LP-437
* A new gateway, controller, service and related config for general partners
* Changed name of the registration controller as there is now also a General Partner controller
* Extracted a common service function into a new utils file
TODO Call the SDK to save the General Partner details
```
```
- BREAKING CHANGE: …
> LP-437 New infrastructure classes to support saving details

- locales/cy/translations.json
- locales/en/translations.json
- src/views/includes/macros.njk
- src/views/pages/address/postcode-form.njk
N/A
remove custom html error message
```
``` …
> remove custom html error message

- src/views/pages/address/postcode-form.njk
https://companieshouse.atlassian.net/browse/LP-538
Postcode lookup form changed - moved find button up above the "enter address manually" link
Tested tab order
```
``` …
> LP-538 Update postcode lookup page layout - swap enter address link and find button

- locales/cy/translations.json
- locales/en/translations.json
- src/views/application-submitted.njk
https://companieshouse.atlassian.net/browse/LP-245
set page title
```
``` …
> LP-245 set page title

- src/infrastructure/gateway/utils.ts
- src/presentation/test/unit/gateway/utils.spec.ts
https://companieshouse.atlassian.net/browse/LP-544
trim extra spaces
```
``` …
> lp-544 : trim extra spaces

- package-lock.json
- package.json
https://companieshouse.atlassian.net/browse/LP-544
date trim
bump sdk version
```
``` …
> lp-544 : bump sdk version

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-616
Fixed typos in translations files
```
``` …
> LP-616 Corrected typo in translations

- package-lock.json
- package.json
- src/application/service/LimitedPartnershipService.ts
- src/domain/IIncorporationGateway.ts
- src/infrastructure/gateway/incorporation/IncorporationGateway.ts
- src/infrastructure/gateway/incorporation/IncorporationInMemoryGateway.ts
- src/presentation/test/unit/registration/createTransactionAndFirstSubmission.spec.ts
https://companieshouse.atlassian.net/browse/LP-617
* Gateway and service changes to support this
* Test updated
```
``` …
> LP-617 Send 'kind' of incorporation upon creation

- src/infrastructure/repository/CacheRepository.ts
https://companieshouse.atlassian.net/browse/LP-536
fix delete key in cookie
```
``` …
> lp-536 : fix delete key in cookie

- src/views/pages/name/options-with-or-without-welsh.njk
https://companieshouse.atlassian.net/browse/LP-620
* Ensure field ids of option choices are unique
* First id still matches the field name in order for API error messaging to work
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …
> LP-620 Fix name ending option text clicking

- src/views/term.njk
https://companieshouse.atlassian.net/browse/LP-607
fix term selection from data 
```
``` …
> lp-607 : term selection from data

- package-lock.json
NA
Fixes 2 security vulnerabilities 
```
``` …
> Npm security fix

- src/infrastructure/gateway/generalPartner/GeneralPartnerGateway.ts
- src/presentation/test/integration/registration/gateway/add-general-partner.test.ts
https://companieshouse.atlassian.net/browse/LP-595
* Correctly reference the date sub-fields
* Amend test
```
``` …
> LP-595 Fix to allow saving DOB on the Add General Partner Person page

- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/address/general-partner-usual-residential-address-territory-choice.test.ts
- src/routes/addressLookUp.ts
- src/views/general-partner-usual-residential-address-territory-choice.njk
https://companieshouse.atlassian.net/browse/LP-550
add post and rearrange layout on page
```
``` …
> LP550 add post and rearrange layout on page

- src/views/general-partner-usual-residential-address-territory-choice.njk
https://companieshouse.atlassian.net/browse/LP-556
Add Matomo interaction for 'Is the general partner's usual residential address in the UK or overseas?' page
```
``` …
> Add Matomo interaction for 'Is the general partner's usual residential address in the UK or overseas?' page

- src/views/layout.njk
N/A
* Minor change to the header definition based on these instructions:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.15.0#:~:text=%3C!%2D%2D%5Bif%20gt%20IE,alt%3D%22%22%3E%0A%3C!%5Bendif%5D%2D%2D%3E
```
``` …
> Use Tudor Crown logo in the GOV UK Header

- src/presentation/controller/AbstractController.ts
https://companieshouse.atlassian.net/browse/LP-596
The base_url import was removed in commit: https://github.com/companieshouse/limited-partnerships-web/commit/3016acb973a856acb663215f2276ce1666329919
A conflict was not highlighted and it was removed on merge creating a compiler error as it is required by a new function added for this ticket.
```
```
- BREAKING …
> LP-596 Missing import due to prev commit

- src/presentation/controller/global/Controller.ts
LP-596
Fix clearCookie deprecation warning, maxAge property should not be provided.
```
``` …
> LP-596 Fix clear cookie deprecation warning

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/generalPartner/address/postcode-usual-residential-address.test.ts
- src/presentation/test/utils.ts
https://companieshouse.atlassian.net/browse/LP-549
* English and Welsh texts changed
* Unit tests updated to use escaped text due to added apostrophe
```
```
- …
> LP-549 Update page texts to match the prototype

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/registration/Routing.ts
- src/presentation/test/integration/registration/generalPartner/address/general-partner-usual-residential-address-territory-choice.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/views/enter-usual-residential-address.njk
- src/views/general-partner-usual-residential-address-territory-choice.njk
- src/views/pages/address/enter-address-fields.njk
https://companieshouse.atlassian.net/browse/LP-553
Added length validation to general partner URA manual entry postcode
Changed limited-partners screen back link to go to general-partners start screen
Cleaned up GP territory choice translation text and test.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
> LP-553 postcode valdation and limited partners back link

- src/views/layout.njk
N/A
* Reference the new crown logo icon from the layout template
```
``` …
> Use Tudor Crown logo in the browser tab

- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-481
Update set page title on the template to use the localisation field.
```
``` …
> LP-481 Check your answers page title

- src/views/sign-out.njk
https://companieshouse.atlassian.net/browse/LP-647
Fix accessibility issue on sign out page around the hidden field
```
``` …
> LP-647 Fix sign-out hidden field for a11y

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-636
updated ROA manual entry page text
```
``` …
> LP-636 Updated text for ROA manual entry page

- locales/cy/translations.json
- locales/en/translations.json
- src/views/postcode-registered-office-address.njk
https://companieshouse.atlassian.net/browse/LP-632
Changed text and removed if statements from page template since text is now the same regardless of jurisdiction (England vs Scotland)
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
> LP-632 Changed page text to updated version

- src/config/app-config.ts
- src/config/constants.ts
https://companieshouse.atlassian.net/browse/LP-706
middleware - exclude healthcheck route
```
``` …
> lp-706 : middleware - exclude healthcheck route

- src/application/service/LimitedPartnershipService.ts
- src/domain/ITransactionGateway.ts
- src/infrastructure/gateway/transaction/TransactionGateway.ts
- src/infrastructure/gateway/transaction/TransactionInMemoryGateway.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/test/integration/mock/sdkMock.ts
- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/presentation/test/integration/registration/gateway/check-your-answers.test.ts
- src/routes/registration.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-660
* New controller, service and gateway functions to close the transaction
* Registration routing on 'check your answers' changed to first close the transaction before redirecting
* Unit tests added
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
> LP-660 Close the transaction related to the LP registration

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/integration/registration/address/postcode-principal-place-of-business-address.test.ts
- src/presentation/test/integration/registration/address/postcode-registered-office-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/postcode-general-partner-correspondence-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/postcode-general-partner-usual-residential-address.test.ts
- src/routes/addressLookUp.ts
- src/views/postcode-general-partner-correspondence-address.njk
https://companieshouse.atlassian.net/browse/LP-711
- Page
- Routing
Covers ACs 5-8, 1-4 will require new pages yet to be added.
```
``` …
> LP-711 Correspondence address postcode lookup page

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/integration/registration/address/enter-principal-place-of-business-address.test.ts
- src/presentation/test/integration/registration/address/enter-registered-office-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/enter-general-partner-correspondence-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/enter-general-partner-principal-office-address.test.ts
- src/routes/addressLookUp.ts
- src/views/enter-general-partner-correspondence-address.njk
https://companieshouse.atlassian.net/browse/LP-710
* Added page for GP Person manual entry of correspondence address
* Routings changed
* Tests added
* AC1 not done as Confirmation page does not yet exist (TODO comments added to code)
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR …
> LP-710 General partner person correspondence address  manual entry

- src/presentation/test/integration/registration/generalPartner/address/confirm-general-partner-usual-residential-address.test.ts
- src/views/confirm-general-partner-principal-office-address.njk
- src/views/confirm-general-partner-usual-residential-address.njk
https://companieshouse.atlassian.net/browse/LP-720
Fix back link from confirm general partner usual residential address when overseas territory is selected.
```
``` …
> LP-720 Fix confirm gp ura address back link

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/builder/GeneralPartnerBuilder.ts
- src/presentation/test/integration/registration/generalPartner/address/confirm-general-partner-correspondence-address.test.ts
- src/routes/addressLookUp.ts
- src/views/confirm-general-partner-correspondence-address.njk
https://companieshouse.atlassian.net/browse/LP-709
- Template and routing
- Update controller to include correspondence address.
```
``` …
> LP-709 Confirm the general partners correspondence page

- sonar-project.properties
- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/integration/registration/generalPartner/address/confirm-general-partner-correspondence-address.test.ts
N/A
fix correspondence address
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, …
> fix correspondence address

- locales/cy/translations.json
- locales/en/translations.json
- src/views/confirm-general-partner-correspondence-address.njk
N/A
fix: confirm correspondence address - remove hidden link translation
```
``` …
> confirm correspondence address - remove hidden link

- locales/cy/translations.json
https://companieshouse.atlassian.net/browse/LP-744
Fix the welsh translation entry for public register information
```
``` …
> LP-744 Fix translations

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/generalPartner/review-general-partners.test.ts
- src/views/review-general-partners.njk
https://companieshouse.atlassian.net/browse/LP-237
fix translation and margin
```
``` …
> lp-237 : fix translation and margin

- src/views/add-general-partner-person.njk
https://companieshouse.atlassian.net/browse/LP-610
Fix a11y error: element was missing a role attribute.
```
```
- types other than `fix:` and `feat:` are allowed, …
> LP-610 Fix a11y issue on GP Person page

- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-606
Updates to conditional showing of term
```
``` …
> LP-606 term updates to display for LP and SLP + change link

- locales/cy/translations.json
- locales/en/translations.json
- src/views/standard-industrial-classification-code.njk
https://companieshouse.atlassian.net/browse/LP-696
added fieldset legend to sic code input fields
```
``` …
> LP-696 added visually hidden labels to input fields + translations

- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-606
Fixed term not showing correctly
mapped term to translation text
added new test for term text
```
```
- types …
> LP-606 correctly display the selected term

- src/views/email.njk
- src/views/name.njk
- src/views/pages/address/postcode-form.njk
https://companieshouse.atlassian.net/browse/LP-510
Removed any data event ids from name, email and postcode input fields.
```
``` …
> Remove Matomo tracking from all text input fields.

- src/views/review-general-partners.njk
https://companieshouse.atlassian.net/browse/LP-762
review page - radio button required
```
``` …
> lp-762 : review page - radio button required

- src/infrastructure/gateway/transaction/TransactionGateway.ts
https://companieshouse.atlassian.net/browse/LP-583
Updated the gateway to pass the new description that includes the word "Registration".
```
```
- types other …
> LP-583 Amend transaction description to include registration

- src/application/service/LimitedPartnerService.ts
- src/domain/ILimitedPartnerGateway.ts
- src/infrastructure/gateway/generalPartner/GeneralPartnerGateway.ts
- src/infrastructure/gateway/limitedPartner/LimitedPartnerGateway.ts
- src/infrastructure/gateway/limitedPartner/LimitedPartnerInMemoryGateway.ts
- src/infrastructure/gateway/utils.ts
- src/presentation/controller/registration/LimitedPartnerController.ts
- src/presentation/test/integration/registration/gateway/add-limited-partner.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/presentation/test/integration/registration/limitedPartner/add-limited-partner-person.test.ts
- src/presentation/test/utils.ts
- src/routes/registration.ts
https://companieshouse.atlassian.net/browse/LP-763
Patch limited partner on add person page
added sendPageData function to controller, gateway and service
```
``` …
> Lp 763 patch limited partner person

- src/config/app-config.ts
- src/config/constants.ts
- src/middlewares/journey.detection.middleware.ts
- src/presentation/controller/AbstractController.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/test/integration/registration/which-type.test.ts
- src/presentation/test/integration/transition/company-number.test.ts
- src/utils/index.ts
- src/utils/journey.ts
- src/views/includes/header.njk
- src/views/layout.njk
https://companieshouse.atlassian.net/browse/LP-664
Make the page banner service name change depending on journey type
```
``` …
> LP-664 Make page banner service name change based on journey type

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/limitedPartner/address/territory-choice-limited-partner-principal-office-address.test.ts
- src/routes/addressLookUp.ts
- src/views/territory-choice-limited-partner-principal-office-address.njk
https://companieshouse.atlassian.net/browse/LP-674
Added page template and endpoints.
```
``` …
> Lp 674 territory limited partner principal office address

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/limitedPartner/address/confirm-limited-partner-principal-office-address.test.ts
- src/routes/addressLookUp.ts
- src/views/confirm-limited-partner-principal-office-address.njk
https://companieshouse.atlassian.net/browse/LP-678
confirm-limited-partner-principal-office-address
```
``` …
> lp-678 : confirm-limited-partner-principal-office-address

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/test/integration/registration/limitedPartner/address/enter-limited-partner-principal-office-address.test.ts
- src/routes/addressLookUp.ts
- src/views/enter-limited-partner-principal-office-address.njk
https://companieshouse.atlassian.net/browse/LP-676
* Added page for LP Legal Entity manual entry of principal office  address
* Routings changed
* Tests added and amended
* AC1 not done as Confirmation page does not yet exist
Further testing required once Limited partner territory choice page is available
```
```
- BREAKING CHANGE: a commit that has a footer …
> LP-676 Limited partner legal entity POA manual entry

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-768
Changed if statements to mapping for term
added mapping for jurisdiction
added test for jurisdiction
```
```
- …
> LP-768 mapping jurisdiction to translation text

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/limitedPartner/add-limited-partner-person.test.ts
- src/views/add-limited-partner-person.njk
- src/views/includes/capital-contribution.njk
https://companieshouse.atlassian.net/browse/LP-777
Covers only the template change required for the capital contribution section on the limited partner person page. The code changes will be done on https://companieshouse.atlassian.net/browse/LP-778
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
> LP-777 Introduce capital contribution section to limited partner person

- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/integration/registration/generalPartner/address/territory-choice-general-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/choose-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/confirm-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/enter-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/postcode-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/territory-choice-limited-partner-usual-residential-address.test.ts
- src/views/confirm-limited-partner-usual-residential-address.njk
- src/views/enter-limited-partner-usual-residential-address.njk
https://companieshouse.atlassian.net/browse/LP-670
lp usual_residential_address address key
```
``` …
> lp-670 : lp usual_residential_address address key

- nodemon.json
- package.json
- src/bin/nodemon-entry.ts
nodemon changes for chs-dev
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, …
> nodemon changes for chs-dev

- src/infrastructure/gateway/utils.ts
- src/presentation/test/unit/gateway/utils.spec.ts
https://companieshouse.atlassian.net/browse/LP-648
type check on removeEmptyStringValues function
```
``` …
> LP-648 type check on removeEmptyStringValues function

- src/middlewares/authentication.middleware.ts
https://companieshouse.atlassian.net/browse/LP-757
signin return url
```
``` …
> lp-757 : signin return url

- locales/cy/translations.json
- locales/en/translations.json
- src/views/postcode-limited-partner-principal-office-address.njk
https://companieshouse.atlassian.net/browse/LP-834
Added hint to the template in the place where they have been added for other postcode pages. 
English and welsh text.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits …
> LP-834 Limited partners principal office address hint text

- package-lock.json
N/A
Security vulnerability fix - created by running 'npm audit fix'
```
``` …
> Latest npm audit fix security upgrades

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-837
Update public register hint text at the bottom of the page to match the prototype.
```
```
- types other than …
> LP-837 Principal office address confirm - amend hint text

- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/controller/registration/Routing.ts
https://companieshouse.atlassian.net/browse/LP-755
back link to gp review page
```
``` …
> lp-755 : back link to gp review page

- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/test/builder/LimitedPartnershipBuilder.ts
- src/presentation/test/integration/registration/where-is-the-jurisdiction.test.ts
https://companieshouse.atlassian.net/browse/LP-716
email page - go to confirm roa if address already saved
```
``` …
> lp-716 : email page  - go to confirm roa

- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/test/integration/registration/address/confirm-registered-office-address.test.ts
- src/presentation/test/integration/registration/email.test.ts
- src/presentation/test/integration/registration/gateway/email.test.ts
- src/presentation/test/integration/registration/where-is-the-jurisdiction.test.ts
https://companieshouse.atlassian.net/browse/LP-832
roa - conditional redirection to poba
```
``` …
> lp-832 : roa - conditionalNextUrl to poba

- src/config/dependencies.ts
- src/config/dev-dependencies.ts
- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/test/integration/registration/generalPartner/review-general-partners.test.ts
https://companieshouse.atlassian.net/browse/LP-836
review gp - go to review lp
```
``` …
> lp-836 : review gp - go to review lp

- src/presentation/controller/addressLookUp/Routing.ts
- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
- src/views/enter-principal-place-of-business-address.njk
https://companieshouse.atlassian.net/browse/LP-782
Updated check your answers template
Fixed bug on template - not picking up principal place of business address data
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits …
> LP-782 Check your answers address change links

- locales/cy/translations.json
- locales/en/translations.json
- src/views/choose-limited-partner-principal-office-address.njk
https://companieshouse.atlassian.net/browse/LP-838
add hint to LP choose poa
```
``` …
> lp-838 : add hint to LP choose poa

- src/infrastructure/gateway/addressLookUp/AddressLookUpInMemoryGateway.ts
- src/presentation/test/integration/registration/address/choose-principal-place-of-business-address.test.ts
- src/presentation/test/integration/registration/address/choose-registered-office-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/choose-general-partner-correspondence-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/choose-general-partner-principal-office-address.test.ts
- src/presentation/test/integration/registration/generalPartner/address/choose-general-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/choose-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/registration/limitedPartner/address/choose-limited-principal-office-address.test.ts
- src/views/includes/macros.njk
https://companieshouse.atlassian.net/browse/LP-809
use 'safe' on the address format macro so it doesn't escape chars.
```
``` …
> LP-809 fix apostrophe escaping and choose address screen

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-652
English and welsh texts updated for this.
```
``` …
> LP-652 Add full stop to general partner territory page text

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-861
English and Welsh texts updated.
```
``` …
> LP-861 Missing full stops

- locales/cy/translations.json
- locales/en/translations.json
- src/application/service/AddressService.ts
- src/presentation/test/integration/registration/address/enter-registered-office-address.test.ts
https://companieshouse.atlassian.net/browse/LP-862
postcode character validation
```
``` …
> lp-862 - postcode character validation

- locales/cy/translations.json
- locales/en/translations.json
- src/views/confirm-general-partner-correspondence-address.njk
- src/views/confirm-general-partner-principal-office-address.njk
- src/views/confirm-general-partner-usual-residential-address.njk
- src/views/confirm-limited-partner-principal-office-address.njk
- src/views/confirm-limited-partner-usual-residential-address.njk
- src/views/enter-general-partner-correspondence-address.njk
- src/views/enter-general-partner-principal-office-address.njk
- src/views/enter-general-partner-usual-residential-address.njk
- src/views/enter-limited-partner-principal-office-address.njk
- src/views/enter-limited-partner-usual-residential-address.njk
- src/views/general-partners.njk
- src/views/includes/back-link.njk
- src/views/includes/sign-out-user-banner.njk
N/A
* Implemented for the 'back' and 'sign out' links
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …
> Ensure banner link text is translated when language changed

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/builder/GeneralPartnerBuilder.ts
- src/presentation/test/builder/LimitedPartnerBuilder.ts
- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
https://companieshouse.atlassian.net/browse/LP-866
fix check your answer - previous names
```
``` …
> lp-866 : fix check your answer - previous names

- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
- src/views/includes/macros.njk
https://companieshouse.atlassian.net/browse/LP-864
https://companieshouse.atlassian.net/browse/LP-865
show county and country on address fields on check your answers page
small change to macro to display all saved data
```
``` …
> Lp 864 display country and county on address cya

- src/application/service/AddressService.ts
- src/application/service/CompanyService.ts
- src/application/service/GeneralPartnerService.ts
- src/application/service/LimitedPartnershipService.ts
- src/presentation/controller/transition/TransitionController.ts
- src/utils/date-format.ts
- src/utils/environment.value.ts
N/A
Fix some of the issues highlighted by Sonar
https://sonarqube.companieshouse.gov.uk/project/issues?issueStatuses=OPEN%2CCONFIRMED&impactSoftwareQualities=MAINTAINABILITY&branch=main&id=uk.gov.companieshouse%3Alimited-partnerships-web
```
``` …
> Sonar fixes

- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/test/integration/registration/gateway/add-general-partner.test.ts
- src/presentation/test/integration/registration/generalPartner/add-general-partner-legal-entity.test.ts
- src/presentation/test/integration/registration/generalPartner/add-general-partner-person.test.ts
https://companieshouse.atlassian.net/browse/LP-849
Use existing lines to reassign the previous url to be the review page. Added a further condition to reassign to the review page whenever there is one or more general partner on the list.
```
``` …
> LP-849 Able to back link to review page for general partners

- src/presentation/controller/registration/LimitedPartnerController.ts
- src/presentation/test/integration/registration/generalPartner/add-general-partner-legal-entity.test.ts
- src/presentation/test/integration/registration/limitedPartner/add-limited-partner-legal-entity.test.ts
- src/presentation/test/integration/registration/limitedPartner/add-limited-partner-person.test.ts
https://companieshouse.atlassian.net/browse/LP-850
Use existing lines to reassign the previous url to be the review page. Added a further condition to reassign to the review page whenever there is one or more limited partner on the list.
```
``` …
> LP-850 Able to back link to review page for limited partners

- src/application/service/AddressService.ts
- src/presentation/test/integration/registration/gateway/addressLookUp.test.ts
https://companieshouse.atlassian.net/browse/LP-474
add check for empty address list
```
``` …
> LP-474 add check for empty address list

- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/test/integration/registration/generalPartner/review-general-partners.test.ts
https://companieshouse.atlassian.net/browse/LP-887
Moved error logic outside of if statement to prevent any action on review page when partner data missing
```
``` …
> LP-887 ensure no progression from review page when incomplete partner data

- README.md
https://companieshouse.atlassian.net/browse/LP-858
Update the readme
```
``` …
> LP-858 Removed start page: update readme

- src/middlewares/error.middleware.ts
- src/presentation/test/integration/error-404.test.ts
- src/presentation/test/integration/error-500.test.ts
- src/presentation/test/integration/error-csrf.test.ts
- src/test/setup-jest.ts
https://companieshouse.atlassian.net/browse/LP-847
fix error pages header
```
``` …
> lp-847 : fix error pages header

- README.md
- locales/cy/translations.json
- locales/en/translations.json
- package-lock.json
- package.json
- src/presentation/test/builder/GeneralPartnerBuilder.ts
- src/views/add-general-partner-legal-entity.njk
- src/views/add-limited-partner-legal-entity.njk
https://companieshouse.atlassian.net/browse/LP-867
* Checkbox field is no longer required on the screen or to be stored by API
```
``` …
> LP-867 Removed Legal Entity partner statement field

- src/views/includes/styles/print.njk
https://companieshouse.atlassian.net/browse/LP-892
remove cookie banner when printing with javascript off
```
``` …
> LP-892 Remove cookie banner from print page when js disabled

- src/config/constants.ts
https://companieshouse.atlassian.net/browse/LP-906
text change for transition banner
```
``` …
> LP-906 change transition banner text

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/transition/LimitedPartnershipController.ts
- src/presentation/controller/transition/PageType.ts
- src/presentation/controller/transition/routing/limitedPartnership.ts
- src/presentation/controller/transition/template.ts
- src/presentation/controller/transition/url.ts
- src/presentation/test/builder/LimitedPartnershipBuilder.ts
- src/presentation/test/integration/registration/email.test.ts
- src/presentation/test/integration/transition/email.test.ts
- src/routes/transition.ts
- src/views/email.njk
- src/views/includes/company-name.njk
https://companieshouse.atlassian.net/browse/LP-879
email template updated for transition
registration email tests updated due to changes in translation file
updates to transition limitedPartnershipController to send page data
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
> Lp 879 transition what is the registered email address

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/controller/registration/LimitedPartnerController.ts
- src/views/includes/capital-contribution.njk
https://companieshouse.atlassian.net/browse/LP-653
- Updated capital contribution template to include the hint text.
- Updated capital contribution template by putting the currency type first.
- Updated controller to fix page render errors.
- Updated capital contribution template to play back contribution types that have previously been ticked.
```
```
- …
> LP-653 Ensure capital contribution hint text is present

- src/config/IDependencies.ts
- src/config/app-config.ts
- src/config/constants.ts
- src/config/dependencies.ts
- src/config/dev-dependencies.ts
- src/domain/entities/journey.ts
- src/presentation/controller/AbstractController.ts
- src/presentation/controller/PageType.ts
- src/presentation/controller/postTransition/LimitedPartnershipController.ts
- src/presentation/controller/postTransition/pageType.ts
- src/presentation/controller/postTransition/routing.ts
- src/presentation/controller/postTransition/routing/limitedPartnership.ts
- src/presentation/controller/postTransition/template.ts
- src/presentation/controller/postTransition/url.ts
- src/presentation/test/integration/global/payment-decision.test.ts
- src/presentation/test/integration/post-transition/company-number.test.ts
- src/presentation/test/integration/post-transition/confirm-limited-partnership.test.ts
- src/presentation/test/unit/registration/createTransactionAndFirstSubmission.spec.ts
- src/routes/index.ts
- src/routes/postTransition.ts
- src/utils/journey.ts
- src/views/confirm-limited-partnership.njk
- src/views/includes/header.njk
https://companieshouse.atlassian.net/browse/LP-917
company-lookup and company-profile pages
```
``` …
> lp-917 : company-lookup and company-profile

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/check-your-answers.test.ts
- src/views/check-your-answers.njk
- src/views/includes/macros.njk
https://companieshouse.atlassian.net/browse/LP-884
- Changed text to html and added a line break so that amount + currency and types of contribution are on separate lines.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of …
> Lp 884 check your answers capital contribution

- src/presentation/controller/global/Controller.ts
- src/presentation/test/integration/global/resume.test.ts
https://companieshouse.atlassian.net/browse/LP-920
set paymentReturnUrl correctly
update to resume.test to correct url
```
``` …
> Lp 920 payment routing issue on retry

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-988
Text change for the Scottish private limited fund partnership option.
```
``` …
> LP-988 Amend which-type page content

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/name.test.ts
- src/views/layout.njk
- src/views/name.njk
https://companieshouse.atlassian.net/browse/LP-999
- Removed old name check hint text
- Removed sensitive words hint section
- Introduced new rules text and links
- Updated name and ending headings
- Removed specific Scottish and private fund text no longer required, from locale files.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> Lp 999 amend name pages' content

- locales/cy/translations.json
- locales/en/translations.json
- src/views/includes/page-title.njk
https://companieshouse.atlassian.net/browse/LP-600
Modified the page-title.njk template to test for errors and add an error prefix if present.
```
```
- types …
> Lp 600 red box add error to tab

- src/presentation/controller/common/GeneralPartnerController.ts
- src/presentation/controller/common/LimitedPartnerController.ts
- src/presentation/controller/registration/GeneralPartnerController.ts
- src/presentation/controller/registration/LimitedPartnerController.ts
- src/presentation/controller/transition/GeneralPartnerController.ts
- src/presentation/controller/transition/LimitedPartnerController.ts
- src/presentation/test/integration/registration/general-partners.test.ts
- src/presentation/test/integration/registration/limited-partners.test.ts
- src/presentation/test/integration/transition/generalPartner/general-partners.test.ts
- src/presentation/test/integration/transition/limitedPartner/limited-partners.test.ts
- src/routes/registration.ts
- src/routes/transition.ts
https://companieshouse.atlassian.net/browse/LP-1000
gp redirect to review page
lp redirect to review pages
```
``` …
> lp-1000 : gp redirect to review pages

- package-lock.json
- package.json
N/A
fix dependencies vulnerability
```
``` …
> fix dependencies vulnerability

- src/views/pages/review-partners.njk
https://companieshouse.atlassian.net/browse/LP-991
Add Matomo event tracking to change/remove links on partner review page
```
``` …
> LP-991 add matomo events for partner review page change/delete links

- src/application/service/GeneralPartnerService.ts
- src/application/service/LimitedPartnerService.ts
- src/domain/IGeneralPartnerGateway.ts
- src/domain/types.ts
- src/infrastructure/gateway/api.ts
- src/presentation/controller/AbstractController.ts
- src/presentation/controller/addressLookUp/Controller.ts
- src/presentation/controller/common/GeneralPartnerController.ts
- src/presentation/controller/common/LimitedPartnerController.ts
- src/presentation/controller/global/Controller.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/controller/transition/LimitedPartnershipController.ts
- src/presentation/test/integration/registration/gateway/email.test.ts
N/A
create common types - token and ids
```
``` …
> create common types

- locales/cy/translations.json
- locales/en/translations.json
https://companieshouse.atlassian.net/browse/LP-1005
confirmation page typo
```
``` …
> lp-1005 : confirmation page typo

- README.md
- locales/cy/translations.json
- locales/en/translations.json
- src/config/constants.ts
- src/presentation/controller/registration/LimitedPartnershipController.ts
- src/presentation/controller/registration/PageType.ts
- src/presentation/controller/registration/routing/limitedPartnership.ts
- src/presentation/controller/registration/template.ts
- src/presentation/controller/registration/url.ts
- src/presentation/test/integration/registration/continue-saved-filing.test.ts
- src/routes/registration.ts
- src/views/continue-saved-filing.njk
https://companieshouse.atlassian.net/browse/LP-545
[LP-545 A new 'continue with a saved filing' page 
* New page added at start of journey
* URLs, routing and config added
* README file updated
* New unit test added
```
``` …
> LP-545 A new 'continue with a saved filing' page

- src/views/includes/phase_banner.njk
https://companieshouse.atlassian.net/browse/LP-1022
Ensure the user can reach the survey page using the beta link on all pages.
```
``` …
> Registration survey links fix

- src/application/service/TransactionService.ts
- src/domain/ITransactionGateway.ts
- src/infrastructure/gateway/transaction/TransactionGateway.ts
- src/infrastructure/gateway/transaction/TransactionInMemoryGateway.ts
- src/presentation/controller/postTransition/GeneralPartnerController.ts
- src/presentation/controller/postTransition/routing/generalPartner.ts
- src/presentation/test/integration/postTransition/generalPartner/add-general-partner-person.test.ts
- src/presentation/test/integration/postTransition/generalPartner/general-partner-choice.test.ts
- src/routes/postTransition.ts
- src/views/add-general-partner-person.njk
https://companieshouse.atlassian.net/browse/LP-948
add general partner person post transition
```
``` …
> LP-948 add general partner person

- src/config/IDependencies.ts
- src/config/dependencies.ts
- src/config/dev-dependencies.ts
- src/presentation/controller/common/LimitedPartnerController.ts
- src/presentation/controller/postTransition/LimitedPartnerController.ts
- src/presentation/controller/postTransition/routing.ts
- src/presentation/controller/postTransition/routing/limitedPartner.ts
- src/presentation/test/builder/LimitedPartnerBuilder.ts
- src/presentation/test/integration/postTransition/limitedPartner/add-limited-partner-person.test.ts
- src/routes/postTransition.ts
- src/views/add-limited-partner-person.njk
https://companieshouse.atlassian.net/browse/LP-966
post-transition - add limited partner person
```
``` …
> lp-966 : add limited partner person

- src/presentation/controller/postTransition/LimitedPartnerController.ts
- src/presentation/controller/postTransition/routing/limitedPartner.ts
- src/presentation/test/integration/postTransition/limitedPartner/add-limited-partner-legal-entity.test.ts
- src/routes/postTransition.ts
- src/views/add-limited-partner-legal-entity.njk
https://companieshouse.atlassian.net/browse/LP-976
Added the routing for the legal entity page.
```
``` …
> LP-976 PT add limited partner legal entity

- src/presentation/controller/addressLookUp/routing/postTransition/limitedPartner.ts
- src/presentation/controller/addressLookUp/routing/postTransition/routing.ts
- src/presentation/test/integration/postTransition/limitedPartner/addresses/choose-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/postTransition/limitedPartner/addresses/confirm-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/postTransition/limitedPartner/addresses/enter-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/postTransition/limitedPartner/addresses/postcode-limited-partner-usual-residential-address.test.ts
- src/presentation/test/integration/postTransition/limitedPartner/addresses/territory-choice-limited-partner-usual-residential-address.test.ts
- src/routes/addressPostTransition.ts
https://companieshouse.atlassian.net/browse/LP-977
post-transition - lp ura address
```
``` …
> lp977 : post-transition - lp ura address

- src/views/email.njk
https://companieshouse.atlassian.net/browse/LP-1100
a11y - add hidden label
```
``` …
> fix : a11y - add hidden label

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/global/confirmation-post-transition.test.ts
- src/presentation/test/integration/global/confirmation.test.ts
- src/views/confirmation.njk
https://companieshouse.atlassian.net/browse/LP-1113
Change confirmation page to show Update submitted on post transition journeys
```
``` …
> LP-1113 Show Update Submitted on post transition confirmation screens

- src/application/service/CompanyService.ts
- src/presentation/controller/common/GeneralPartnerController.ts
- src/presentation/controller/common/LimitedPartnerController.ts
- src/presentation/controller/global/Controller.ts
- src/presentation/controller/postTransition/GeneralPartnerController.ts
- src/presentation/controller/postTransition/LimitedPartnerController.ts
- src/presentation/controller/postTransition/LimitedPartnershipController.ts
- src/presentation/controller/transition/LimitedPartnershipController.ts
- src/views/confirm-limited-partnership.njk
- src/views/landing-page.njk
https://companieshouse.atlassian.net/browse/LP-1065
Refactor to do the mapping of company profile into limited partnership in CompanyService
```
```
- types other …
> LP-1065 Refactor to map company profile into limited partnership

- src/views/confirmation.njk
https://companieshouse.atlassian.net/browse/LP-1089
Record survey link click.
```
``` …
> LP-1089 Matomo record confirmation page survey link

- src/config/constants.ts
- src/presentation/controller/postTransition/GeneralPartnerController.ts
- src/presentation/controller/postTransition/LimitedPartnerController.ts
- src/presentation/controller/postTransition/LimitedPartnershipController.ts
https://companieshouse.atlassian.net/browse/LP-1065
Fix transaction description for Update limited partnership details and created constants for the other post transition descriptions 
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
> LP-1065 fix transaction description

- src/views/date-of-update.njk
https://companieshouse.atlassian.net/browse/LP-1066
Added set title to template.
```
``` …
> LP-1066 Change date -  missing page heading on the tab

- src/infrastructure/gateway/limitedPartnership/LimitedPartnershipInMemoryGateway.ts
- src/presentation/controller/postTransition/LimitedPartnershipController.ts
- src/presentation/test/integration/postTransition/limitedPartnership/enter-registered-office-address.test.ts
- src/presentation/test/unit/registration/updateSubmission.spec.ts
https://companieshouse.atlassian.net/browse/LP-1090
fix error re-render
```
``` …
> lp-1090 : fix error re-render

- src/config/dependencies.ts
- src/config/dev-dependencies.ts
- src/presentation/controller/postTransition/LimitedPartnershipController.ts
- src/presentation/test/integration/postTransition/limitedPartnership/checkYourAnswer/partnership-name-change-check-your-answers.test.ts
- src/routes/postTransition.ts
- src/views/pages/checkYourAnswersChange/partnershipName.njk
https://companieshouse.atlassian.net/browse/LP-1122
add payment
```
``` …
> lp-1122 : add payment

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/global/confirmation-post-transition.test.ts
- src/views/includes/update-confirmation-message.njk
https://companieshouse.atlassian.net/browse/LP-1185
Added the term subtype to the template.
```
``` …
> LP-1185 Post transition Updating Term - Confirmation page

- src/presentation/test/integration/postTransition/limitedPartnership/dateOfUpdate/when-did-the-name-of-the-partnership-change.test.ts
- src/views/includes/proposed-name.njk
https://companieshouse.atlassian.net/browse/LP-1252
PT - append the name ending if it exists
```
``` …
> lp-1252 : append the name ending if it exists

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/registration/name.test.ts
https://companieshouse.atlassian.net/browse/LP-1213
Locales and tests update to accommodate changes.
```
``` …
> Lp 1213 name page content changes

- locales/cy/translations.json
- locales/en/translations.json
- src/presentation/test/integration/global/confirmation-post-transition.test.ts
- src/presentation/test/integration/postTransition/limitedPartnership/checkYourAnswer/principal-place-of-business-address-change-check-your-answers.test.ts
- src/views/includes/update-confirmation-message.njk
https://companieshouse.atlassian.net/browse/LP-1180
Updated template and locales to include this page.
```
```
- types other than `fix:` and `feat:` are allowed, …
> LP-1180 Post transition - principal place of business confirmation page

- src/application/service/CompanyService.ts
- src/presentation/controller/postTransition/routing/limitedPartnership.ts
- src/presentation/test/builder/CompanyProfileBuilder.ts
- src/presentation/test/integration/postTransition/limitedPartnership/enter-principal-place-of-business-address.test.ts
- src/presentation/test/unit/postTransition/companyService.test.ts
https://companieshouse.atlassian.net/browse/LP-1290
map ppob address
```
``` …
> lp-1290 : map ppob address
